pub_index:
    path: /
    controller: App\Controller\Pub\IndexController::index
pub_contact:
    path: /contact
    controller: App\Controller\Pub\ContactController::index
pub_login:
    path: /login
    controller: App\Controller\Pub\LoginController::index
pub_signup:
    path: /signup
    controller: App\Controller\Pub\SignupController::index


priv_pannel:
    path: /pannel
    controller: App\Controller\Priv\PannelController::index
priv_admin:
    path: /admin
    controller: App\Controller\Priv\AdminController::index
