pub_index:
    path: /
    controller: App\Controller\Pub\IndexController::index
pub_contact:
    path: /contact
    controller: App\Controller\Pub\ContactController::index
pub_login:
    path: /login
    controller: App\Controller\Pub\LoginController::index
